/**
 * Context Injection Store — writes Weplex workspace context into CLAUDE.local.md
 * (gitignored by Claude Code convention). Gives Claude passive awareness of
 * the current space, other sessions, and cost without extra prompting.
 * Writes are idempotent — skipped when content hasn't changed (diff check in Rust).
 */

import { invoke } from '@tauri-apps/api/core';
import { sessionStore } from './sessionStore.svelte';
import { spaceStore } from './spaceStore.svelte';
import { profileStore } from './profileStore.svelte';
import { workflowStore } from './workflowStore.svelte';
import type { Session } from '../types';

// ── Sanitization ────────────────────────────────────────────────────────────

/** Sanitize interpolated values to prevent context block injection. */
function sanitizeCtx(value: string): string {
  return value
    .replace(/<!--/g, '')     // strip HTML comment openers (prevents breaking block markers)
    .replace(/-->/g, '')      // strip HTML comment closers
    .replace(/^#+\s/gm, '')   // strip markdown heading syntax (prevents heading injection)
    .replace(/[\x00-\x08\x0B-\x0C\x0E-\x1F]/g, ''); // strip control chars
}

// ── Context block builder ────────────────────────────────────────────────────

function buildContextBlock(session: Session): string {
  const space = spaceStore.spaces.find((s) => s.id === session.spaceId);
  const spaceName = sanitizeCtx(space?.name || 'Default');

  // Gather other sessions in the same space
  const otherSessions = sessionStore.sessions
    .filter((s) => s.spaceId === session.spaceId && s.id !== session.id && s.status !== 'new')
    .map((s) => {
      const status = s.status === 'active' ? 'active' : s.status === 'waiting' ? 'waiting' : 'idle';
      const cwd = s.cwd ? ` — ${s.cwd}` : '';
      const agent = s.agentType ? ` (${s.agentType})` : '';
      return `    - ${sanitizeCtx(s.name)}${agent} [${status}]${cwd}`;
    });

  // Profile info
  const profileId = session.profileId || space?.profileId;
  const profile = profileId ? profileStore.getById(profileId) : profileStore.defaultProfile;
  const profileName = sanitizeCtx(profile?.name || 'Default');
  const sessionName = sanitizeCtx(session.name || 'Session');

  // Build the block
  const lines: string[] = [
    '<!-- wplx-ctx — auto-generated by Weplex, do not edit this block -->',
    '## Weplex Workspace Context',
    `- Space: ${spaceName} | Session: ${sessionName} | Profile: ${profileName}`,
  ];

  if (otherSessions.length > 0) {
    lines.push('- Active sessions in this space:');
    lines.push(...otherSessions);
  }

  // Workflow instructions
  const workflowInstructions = workflowStore.getInstructions(session.workflowId);
  if (workflowInstructions) {
    lines.push('');
    lines.push('## Workflow Instructions');
    lines.push(sanitizeCtx(workflowInstructions));
  }

  lines.push('<!-- /wplx-ctx -->');

  return lines.join('\n');
}

// ── Public API ───────────────────────────────────────────────────────────────

export const contextInjectionStore = {
  /**
   * Write Weplex context into the project's CLAUDE.local.md.
   * Only writes for Claude agent sessions with a known cwd.
   * Idempotent — Rust side skips write if content unchanged.
   */
  async inject(session: Session): Promise<void> {
    if (session.agentType !== 'claude' || !session.cwd) return;

    const contextBlock = buildContextBlock(session);

    try {
      await invoke('inject_context_block', {
        cwd: session.cwd,
        contextBlock,
      });
    } catch (e) {
      console.error('[weplex] Failed to write CLAUDE.local.md context:', e);
    }
  },
};
