<script lang="ts">
  import {
    Terminal,
    Code,
    Bug,
    Rocket,
    Bot,
    Wrench,
    Zap,
    Server,
    Database,
    Globe,
    Lock,
    Shield,
    Cpu,
    Cloud,
    Layers,
    GitBranch,
    Package,
    Box,
    Key,
    Eye,
    Search,
    Monitor,
    Network,
    Wifi,
    Star,
    Heart,
    Bookmark,
    Flag,
    Bell,
    Command,
    Coffee,
    Flame,
    Lightbulb,
    Sparkles,
    Brain,
    Atom,
    Moon,
    Sun,
    Palette,
    Music,
    Gamepad2,
    Radio,
    Home,
    Users,
    FileText,
    Link,
    Send,
    Fingerprint,
  } from 'lucide-svelte';

  let { icon, size = 12 }: { icon: string; size?: number } = $props();

  const LUCIDE_MAP: Record<string, any> = {
    terminal: Terminal,
    code: Code,
    bug: Bug,
    rocket: Rocket,
    bot: Bot,
    wrench: Wrench,
    zap: Zap,
    server: Server,
    database: Database,
    globe: Globe,
    lock: Lock,
    shield: Shield,
    cpu: Cpu,
    cloud: Cloud,
    layers: Layers,
    'git-branch': GitBranch,
    package: Package,
    box: Box,
    key: Key,
    eye: Eye,
    search: Search,
    monitor: Monitor,
    network: Network,
    wifi: Wifi,
    star: Star,
    heart: Heart,
    bookmark: Bookmark,
    flag: Flag,
    bell: Bell,
    command: Command,
    coffee: Coffee,
    flame: Flame,
    lightbulb: Lightbulb,
    sparkles: Sparkles,
    brain: Brain,
    atom: Atom,
    moon: Moon,
    sun: Sun,
    palette: Palette,
    music: Music,
    gamepad2: Gamepad2,
    radio: Radio,
    home: Home,
    users: Users,
    'file-text': FileText,
    link: Link,
    send: Send,
    fingerprint: Fingerprint,
  };

  let isLucide = $derived(icon?.startsWith('lucide:') ?? false);
  let lucideName = $derived(isLucide ? icon.slice(7) : '');
  let LucideComp = $derived(isLucide ? (LUCIDE_MAP[lucideName] ?? null) : null);
</script>

{#if isLucide && LucideComp}
  {@const Comp = LucideComp}
  <Comp {size} />
{:else}
  {icon}
{/if}
